config/routes.rb
AccOnline::Application.routes.draw do
  devise_for :admins

  devise_for :users, controllers: {
    sessions:       "users/sessions",
    passwords:      "users/passwords",
    registrations:  "users/registrations"
  }

  match "/admin", :to => "admin/dashboard#index"
  namespace :admin do
    resources :admins, :program_categories
    resource :profile

    resources :packages do
      resources :package_programs
    end

    resources :services do
      member do
        put "disable"
        put "enable"
        put "reset_token"
      end

      resources :job_titles, :controller => "services/job_titles"
      resources :programs, :controller => "services/programs"
      resources :users, :controller => "services/users", :only => [:index]
      resources :user_imports

      resources :questionable, controller: "services/questionable"
      resources :learning_plans, :controller => "services/learning_plans", :only => [:index, :show]
      resources :employments do
        member do
          put "end"
        end
      end
    end

    resources :users do
      resources :employments
      resources :learning_plans, only: [:index, :show], controller: 'users/employment_learning_plans'
      resources :activities, controller: "users/activities", only: [:index]
      resource :passwords do
        member do
          put "reset"
        end
      end
    end

    resources :programs do
      resources :assessments, controller: "programs/assessments", as: :program_assessments

      resources :learning_resources do
        member do
          get :download
        end
      end
    end

    resources :program_assessment_sections do
      resources :fill_gap_questions,
        controller: "programs/assessments/sections/fill_gap_questions",
        as: :program_assessment_fill_gap_questions

      resources :true_or_false_questions,
        controller: "programs/assessments/sections/true_or_false_questions",
        as: :program_assessment_true_or_false_questions

      resources :multiple_choice_questions,
        controller: "programs/assessments/sections/multiple_choice_questions",
        as: :program_assessment_multiple_choice_questions

      resources :sequential_questions,
        controller: "programs/assessments/sections/sequential_questions",
        as: :program_assessment_sequential_questions

      resources :matching_task_questions,
        controller: "programs/assessments/sections/matching_task_questions",
        as: :program_assessment_matching_task_questions
    end

    resources :groups do
      resources :services
      resources :job_titles, controller: "groups/job_titles"
      resources :users, :controller => "groups/users"
      resources :coordinators, :controller => "groups/coordinators"
      resources :programs, :controller => "groups/programs"

      member do
        put "disable"
        put "enable"
      end
    end

    resources :style_guides, only: ['show']
  end

  namespace :api do
    resources :groups do
      resources :coordinators, :controller => "groups/coordinators"
      resources :job_titles, :controller => "groups/job_titles"
      resources :services
      resources :charts, controller: "groups/charts"

      resources :program_assessments, controller: "groups/program_assessments" do
        collection do
          post "update_all"
        end
      end
    end

    resources :role do
      resources :services
    end

    resources :services do
      member do
        put "reset_token"
        put "export_services_information"
        put "export_groups_services_information"
      end

      resources :program_assessments, controller: "services/program_assessments" do
        collection do
          post "update_all"
        end
      end

      resources :charts, controller: "services/charts"
      resources :employments, :controller => "services/employments" do
        collection do
          get "advanced"
          post "advanced"
        end
      end

      resources :job_titles, :controller => "services/job_titles"
      resources :users, :programs
      resources :learning_plans, :controller => "services/learning_plans"
      resources :user_imports, :controller => "services/user_imports"
      resources :group_sessions, :controller => "services/group_sessions"

    end

    resources :employment_learning_plans do
      resources :programs_pending, controller: "employment_learning_plans/programs_pending"
      resources :programs_completed, controller: "employment_learning_plans/programs_completed"
    end

    resources :employments do
      resources :learning_plans, :controller => "services/employment_learning_plans"
      resources :activities, controller: "employments/activities"
      resources :program_assessments, controller: "employments/program_assessments"
    end

    resources :programs do
      resources :assessments, controller: "programs/assessments"
      resources :learning_records, :controller => "programs/learning_records"
      resources :learning_resources, :controller => "programs/learning_resources"
      resources :related, controller: "programs/related"
      resources :videos, controller: "programs/videos"
    end

    resources :program_assessments do
      resources :sections, controller: "programs/assessments/sections"
      resources :results, controller: "programs/assessments/results"
    end

    resources :program_assessment_sections do
      resources :questions, controller: "programs/assessments/sections/questions"
    end

    resources :learning_plans do
      resources :programs, controller: "learning_plans/programs"
      resources :employments, controller: "learning_plans/employments"
      resources :employment_learning_plans, controller: "learning_plans/employment_learning_plans"
    end

    resource :profile do
      resource :password, :controller => "profiles/password"
      resources :learning_plans, :controller => "profiles/employment_learning_plans"
      resources :coordinators, controller: "profiles/coordinators"
      resources :activities, controller: "profiles/activities"
      resources :assessments, controller: "profiles/assessments"

      resources :employments, :controller => "profiles/employments" do
        member do
          put "finish"
        end
      end
    end
  end

  namespace :webhooks do
    # For testing the connection when configuring in Mandrill
    get "mandrill_event_bulk_update", to: "mandrill_event_bulk_updates#create"

    resource :mandrill_event_bulk_update, only: [:create]

    get "/zendesk/authorize", to: "zendesk#authorize"
    post "/zencoder/:id", :to => "zencoder#update"
  end

  # Backbone views
  get "/dashboard", to: "welcome#index"
  get "/programs", to: "welcome#index"
  get "/programs/*views", to: "welcome#index"
  get "/my-learning/*views", to: "welcome#index"
  get "/my-learning", to: "welcome#index"
  get "/coordinator", to: "welcome#index"
  get "/coordinator/*views", to: "welcome#index"
  get "/settings", to: "welcome#index"

  get "mailers/:id", :to => "mailers#index"
  get "mailers", :to => "mailers#index"

  # Wireframes
  namespace :admin do
    get "wireframes/:id", to: "wireframes#index"
    get "wireframes", to: "wireframes#index"
  end

  # TODO: Merge the two wireframes directories together
  get "wf/:id", :to => "wf#index"
  get "wf", :to => "wf#index"

  get "wireframes/:id", :to => "wireframes#index"
  get "wireframes", :to => "wireframes#index"

  root :to => "welcome#index"

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/views/admin/admins/_form.html.haml
= simple_form_for [:admin, @admin], html: {class: 'form-horizontal'} do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :email, as: :email
  = f.input :role, as: :radio_buttons, collection: @roles if can? :manage, Admin
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/admin/admins/_last_updated_by.html.haml
= admin.updated_by.name + ',' if admin.updated_by
= distance_of_time_in_words_to_now admin.updated_at
ago

app/views/admin/admins/edit.html.haml
= content_for :title do
  Edit Admin -
  = @admin.name

= content_for :contextual_menu do
  .btn-group
    = link_to admin_admin_path(@admin), class: 'btn btn-large tip-bottom', title: 'Show Admin' do
      %i.icon-admins
    = link_to admin_admins_path, class: 'btn btn-large tip-bottom', title: 'Show Admins' do
      %i.icon-bolt

.widget-box
  .widget-title
    %h5 Edit
  .widget-content.nopadding
    = render partial: 'form'

app/views/admin/admins/index.csv.erb
first_name,last_name,email,sign_in_count,last_sign_in_at
<% for admin in @admins %><%= [admin.first_name, admin.last_name, admin.email, admin.sign_in_count, admin.current_sign_in_at].join(",") %>
<% end %>

app/views/admin/admins/index.html.haml
= content_for :title do
  Admins

= content_for :contextual_menu do
  .btn-group
    - if can? :create, Admin
      = link_to new_admin_admin_path, class: 'btn btn-large tip-bottom', title: 'New Admin' do
        %i.icon-plus
    = link_to admin_admins_path(format: :csv), class: 'btn btn-large tip-bottom', title: 'Export Admins' do
      %i.icon-download

.widget-box
  .widget-content.nopadding
    %table.table.table-bordered.table-striped.quicksearch-target
      %thead
        %tr
          %th= Admin.human_attribute_name(:name)
          %th= Admin.human_attribute_name(:email)
          %th= Admin.human_attribute_name(:last_updated_by)
          %th= Admin.human_attribute_name(:last_logged_in)
          %th
      %tbody
        - for admin in @admins
          %tr
            %td= link_to admin, admin_admin_path(admin)
            %td= mail_to admin.email, admin.email
            %td= render 'last_updated_by', admin: admin
            %td= last_logged_in(admin)
            %td
              = link_to 'Show', admin_admin_path(admin) if can? :view, Admin
              |
              = link_to 'Edit', edit_admin_admin_path(admin) if can? :manage, Admin

= content_for :search do
  = text_field_tag :search_field, params[:search_field], placeholder: 'Search Admins', class: 'quicksearch'
  = button_tag "Search", type: 'submit', class: 'tip-right', title: 'Search' do
    %i.icon-search.icon-white

app/views/admin/admins/new.html.haml
= content_for :title do
  New Admin

= content_for :contextual_menu do
  .btn-group
    = link_to admin_admins_path, class: 'btn btn-large tip-bottom', title: 'Show Admins' do
      %i.icon-bolt

.widget-box
  .widget-title
    %h5 New
  .widget-content.nopadding
    = render partial: 'form'

app/views/admin/admins/show.html.haml
= content_for :title do
  Admin -
  = @admin.name

= content_for :contextual_menu do
  .btn-group
    - if can? :update, Admin
      = link_to edit_admin_admin_path(@admin), class: 'btn btn-large tip-bottom', title: 'Edit Admin' do
        %i.icon-pencil
    - if can? :destroy, Admin
      = link_to admin_admin_path(@admin), method: :delete, class: 'btn btn-large btn-danger tip-bottom', title: 'Delete Admin', confirm: "Are you sure you want to DELETE the admin #{@admin.name}? This action cannot be undone." do
        %i.icon-minus

.widget-box
  .widget-content.nopadding
    %table.table.table-bordered.table-striped
      %tbody
        %tr
          %td= Admin.human_attribute_name(:name)
          %td= @admin.name
        %tr
          %td= Admin.human_attribute_name(:email)
          %td= mail_to @admin.email, @admin.email
        %tr
          %td= Admin.human_attribute_name(:role)
          %td= @admin.role.titleize
        %tr
          %td= Admin.human_attribute_name(:last_updated_by)
          %td= render 'last_updated_by', admin: @admin
        %tr
          %td= Admin.human_attribute_name(:last_logged_in)
          %td= last_logged_in(@admin)
        %tr
          %td Created At
          %td #{@admin.created_at.to_s(:long_ordinal)} by #{@admin.name}
        %tr
          %td Updated At
          %td #{@admin.updated_at.to_s(:long_ordinal)} by #{@admin.name}